Inventory
Logan-dlp/PFE-E-ARTSUP pull request #4
Opened 2024-12-04 09:56 UTC by LahessAimere

L'inventaire est un Scriptable Object. On a le choix entre l'inventaire **Player** ou l'inventaire **Cellar**. On peut _ajouter_ et _retirer_ des items dans l'inventaire **Player**, et on peut _envoyer_ les items de l'inventaire **Player** vers l'inventaire **Cellar**. J'ai ajouté des touches personnelles dans l'éditeur pour rendre le tout plus lisible pour tout le monde, y compris pour les de graphs.

2024-12-06 11:07 UTC, DomePuma commented on Assets/_Core/Scripts/ScriptableObjects/ItemData.cs
> +        set => _objectName = value;
Pourquoi avoir ajouté des setter alors que les items sont juste censés être défini par les dev, et le joueur ni le code n'est censé les modifier ?

2024-12-06 11:09 UTC, DomePuma requested changes
- Pour le Canvas Inventory Player t'as oublié d'assigner le préfab de slot dans Inventory UI

Faudra l'améliorer en rajoutant la possibilité de se déplacer case par case dans l'inventaire pour pouvoir décider de quel objet jeter, mais sinon ça a l'air good sur le reste sauf pour les setter que je suis pas sûr de comprendre

Tous les codes editor j'ai pas regardé vu que je suis une brêle, je laisse Logan review ça

2024-12-06 11:26 UTC, LahessAimere commented
> * Pour le Canvas Inventory Player t'as oublié d'assigner le préfab de slot dans Inventory UI
> 
> Faudra l'améliorer en rajoutant la possibilité de se déplacer case par case dans l'inventaire pour pouvoir décider de quel objet jeter, mais sinon ça a l'air good sur le reste sauf pour les setter que je suis pas sûr de comprendre
> 
> Tous les codes editor j'ai pas regardé vu que je suis une brêle, je laisse Logan review ça

" Pour le Canvas Inventory Player t'as oublié d'assigner le préfab de slot dans Inventory UI"
Normal il y a déjà un nombre défini de slots pas besoin de rajouter le prefab, j'ai mis que pour l'inventaire de l'armoire vu que c'est des slots infini donc il faut rajouter des lignes de slots à chaque fois

2024-12-06 11:30 UTC, LahessAimere commented on Assets/_Core/Scripts/ScriptableObjects/ItemData.cs
> +        set => _objectName = value;
je sais pas ça m'a juste stressé mdrr j'enlève ça

2024-12-06 22:30 UTC, DomePuma approved these changes

2024-12-09 13:49 UTC, Logan-dlp requested changes
Es-ce que ça c'est normal ?
![image](https://github.com/user-attachments/assets/8288dc00-935e-427a-a508-8d6960032818)
Attention au namespace

En vrai tous ce je dis là c'est pas grave en soit tout fonctionne

2024-12-09 13:49 UTC, Logan-dlp commented on Assets/_Core/Scripts/Inventory/TransferItemsToOtherInventory.cs
> +public class TransferItemsToOtherInventory : MonoBehaviour
Pourquoi ne pas faire une fonction dans Inventory (ou meme directement dans le scriptable object de l'inventaire)
tu lui met en surcharge un autre inventaire
ceci dis ça fonctionne alors c'est si t'a le courage

2024-12-09 13:49 UTC, Logan-dlp commented on Assets/_Core/Scripts/Inventory/TransferItemsToOtherInventory.cs
> +        if (_inventoryUIPlayer == null)
Pour ça tu peux utiliser [Require Component](https://docs.unity3d.com/6000.0/Documentation/ScriptReference/RequireComponent.html)

2024-12-09 13:49 UTC, Logan-dlp commented on Assets/_Core/Scripts/Inventory/TransferItemsToOtherInventory.cs
> +        if (_inventorySends == null || _inventoryReceives == null)
Tu connais le try / catch ?

2024-12-09 13:49 UTC, Logan-dlp commented on Assets/_Core/Scripts/Inventory/InventoryUI.cs
> +    public void OnAddItemButtonClicked(ItemData item)
Pourquoi tu découpe en plein de petite fonction c'est compliquer a lire je trouve

2024-12-09 13:49 UTC, Logan-dlp commented on Assets/_Core/Scripts/Inventory/InventoryUI.cs
> +    public void OnRemovedItemButtonClicked(ItemData item)
La même

2024-12-09 13:55 UTC, LahessAimere commented on Assets/_Core/Scripts/Inventory/TransferItemsToOtherInventory.cs
> +        if (_inventoryUIPlayer == null)
c'est que que toi tu l'utilises beaucoup mdrr, je vais changer ça

2024-12-09 13:56 UTC, LahessAimere commented on Assets/_Core/Scripts/Inventory/InventoryUI.cs
> +    public void OnAddItemButtonClicked(ItemData item)
je comprend pas ? pourquoi tu voudrais que je fasse ça en une seule fonction ?

2024-12-09 15:11 UTC, LahessAimere commented on Assets/_Core/Scripts/Inventory/InventoryUI.cs
> +    public void OnAddItemButtonClicked(ItemData item)
j'ai capté

2024-12-09 15:19 UTC, LahessAimere commented on Assets/_Core/Scripts/Inventory/TransferItemsToOtherInventory.cs
> +        if (_inventorySends == null || _inventoryReceives == null)
Je vais essayer tu me dira

2024-12-09 15:54 UTC, LahessAimere commented on Assets/_Core/Scripts/Inventory/TransferItemsToOtherInventory.cs
> +        if (_inventorySends == null || _inventoryReceives == null)
Tu l'utilises dans quel genre de cas du coup ?

2024-12-10 09:20 UTC, Logan-dlp approved these changes

2024-12-10 09:20 UTC, merged