Quick time event system
Logan-dlp/PFE-E-ARTSUP pull request #6
Opened 2024-12-09 16:17 UTC by DomePuma

Tout le système de QTE

Force à vous mdrrr

2024-12-10 10:20 UTC, Logan-dlp requested changes
surtout de la nomenclature à revoir en soit je demande pas que tu revois le code vu que c'est du protos

attention au namespace

2024-12-10 10:20 UTC, Logan-dlp commented on Assets/_Core/Scripts/Events/QuickTimeEvent.cs
> +    private enum InputCommand
Erreur de nomenclature voir ligne 21

2024-12-10 10:20 UTC, Logan-dlp commented on Assets/_Core/Scripts/Events/QuickTimeEvent.cs
> +    private enum QTEInputType
Pareil

2024-12-10 10:20 UTC, Logan-dlp commented on Assets/_Core/Scripts/Events/QuickTimeEvent.cs
> +    private class _customQTEButton
pareil

2024-12-10 10:20 UTC, Logan-dlp commented on Assets/_Core/Scripts/Events/QuickTimeEvent.cs
> +    private void Awake()
ça manque d'air ici

2024-12-10 10:20 UTC, Logan-dlp commented on Assets/_Core/Scripts/Events/QuickTimeEvent.cs
> +            case QTEInputType.OneInputRandom:
Test avec or pour la ligne 102 et 105

2024-12-10 10:20 UTC, Logan-dlp commented on Assets/_Core/Scripts/Events/QuickTimeEvent.cs
> +    [SerializeField] private bool isStirProgressBar;
Les nomenclature frrr

2024-12-10 10:20 UTC, Logan-dlp commented on Assets/_Core/Scripts/Events/QuickTimeEvent.cs
> +    [SerializeField] private Sprite[] _buttonSprites;
rajoute array derrière pour pas le confondre avec une liste

2024-12-10 10:20 UTC, Logan-dlp commented on Assets/_Core/Scripts/Events/QuickTimeEvent.cs
> +        switch (inputCommand)
Je suis pas sur que le switch soit approprié dans ce cas

2024-12-10 10:20 UTC, Logan-dlp commented on Assets/_Core/Scripts/Events/QuickTimeEvent.cs
> +using Random = UnityEngine.Random;
Regarde si tu peu supprimer des using

2024-12-11 10:22 UTC, DomePuma commented on Assets/_Core/Scripts/Events/QuickTimeEvent.cs
> +    private enum InputCommand
Ratio

2024-12-11 11:06 UTC, Logan-dlp approved these changes
C'est good pour moi juste fait attention au using y'en a qui servent a rien

2024-12-11 11:24 UTC, closed without merging