Player holding item
Logan-dlp/PFE-E-ARTSUP pull request #8
Opened 2024-12-17 16:30 UTC by DomePuma

2024-12-19 09:38 UTC, Logan-dlp requested changes
Attention à la nomenclature à part ça ça fonctionne donc c'est good 
PS : les commentaire sur la façon de faire les get set n'est pas obligatoire c'est juste plus lisible
```cs
// Exemple
public auto MaVar { get; set; }
```

2024-12-19 09:38 UTC, Logan-dlp commented on Assets/_Core/Scripts/Players/PlayerInteraction.cs
> +        [SerializeField] private GameObject _itemInHand;
Erreur de nomenclature avec la ligne 15

2024-12-19 09:38 UTC, Logan-dlp commented on Assets/_Core/Scripts/Players/PlayerHoldItem.cs
> +    private ItemData _item;
erreur de nomenclature avec la ligne 11
tu peux aussi directement faire ça
```cs
public ItemData Item { get; set; }
```

2024-12-19 09:38 UTC, Logan-dlp commented on Assets/_Core/Scripts/Players/PlayerHoldItem.cs
> +    private GameObject _itemHold;
Pareil que le commentaire précédent avec la ligne 16

2024-12-19 09:38 UTC, Logan-dlp commented on Assets/_Core/Scripts/Players/PlayerHoldItem.cs
> +    public GameObject ItemHold
Manque d'aération

2024-12-19 09:38 UTC, Logan-dlp commented on Assets/_Core/Scripts/Item/ItemDataHolder.cs
> +    [SerializeField] private ItemData _itemData;
T'es pas oubligé mais tu peux aussi utiliser le GET SET

2024-12-19 09:38 UTC, Logan-dlp commented on Assets/_Core/Scripts/Item/ItemData.cs
> +    public GameObject ItemPrefab
Manque d'aeration

2024-12-19 09:38 UTC, Logan-dlp commented on Assets/_Core/Scripts/CookingMachine/WaitingTable.cs
> +    private GameObject[] _itemGameObjectArray = new GameObject[10];
Manque d'aération ici

2024-12-19 11:50 UTC, DomePuma commented on Assets/_Core/Scripts/Players/PlayerInteraction.cs
> +        [SerializeField] private GameObject _itemInHand;
Je vois pas l'erreur ?

2025-01-08 15:34 UTC, Logan-dlp approved these changes
C'est good pour moi
Faudra pas oublier de mettre tout les namespaces par la suite 
je te valide ça

2025-01-09 14:03 UTC, merged